### ISSUE TITLE
I want this

### ISSUE THREAD

**Issue by tbranyen** [STRML/js-slack-bot#1]
And I don't even know what it really is yet...

**Comment by STRML** [comment]
:+1: stupid simple, coming soon!

**Comment by STRML** [comment]
@tbranyen Try it out, I'm running it on Triton in a regional Slack channel and it works really well now. Immune to all kinds of bad stuff like infinite loops and sandboxed pretty well. We're having a good time trying to break it.

**Comment by tbranyen** [comment]
Awesome, nice work, I'll get it into the Netflix #js slack channel :stuck_out_tongue:
